// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`

  LOGIN_ME
  LOGIN_REQUEST
  LOGIN_SUCCESS
  LOGIN_FAILURE
  LOGOUT

  SIGNUP_REQUEST
  SIGNUP_SUCCESS
  SIGNUP_FAILURE

  FORGOT_PASSWORD_REQUEST
  FORGOT_PASSWORD_SUCCESS
  FORGOT_PASSWORD_FAILURE

  RESET_PASSWORD_REQUEST
  RESET_PASSWORD_SUCCESS
  RESET_PASSWORD_FAILURE

  UPDATE_PASSWORD_REQUEST
  UPDATE_PASSWORD_SUCCESS
  UPDATE_PASSWORD_FAILURE

`)
